packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@ziglang/cli': true
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  '@ziglang/cli@0.0.14': '.patches/@ziglang+cli@0.0.14.patch'
