packages:
  - "apps/*"
  - "packages/*"
supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
allowBuilds:
  '@ziglang/cli': true
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  '@ziglang/cli@0.0.14': '.patches/@ziglang+cli@0.0.14.patch'
