/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as VaultsRouteImport } from './routes/vaults'
import { Route as VaultDetailRouteImport } from './routes/vault-detail'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletsIndexRouteImport } from './routes/wallets.index'
import { Route as WalletsWalletIdRouteImport } from './routes/wallets.$walletId'
import { Route as VaultsVaultIdRouteImport } from './routes/vaults.$vaultId'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsRoute = VaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultDetailRoute = VaultDetailRouteImport.update({
  id: '/vault-detail',
  path: '/vault-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsIndexRoute = WalletsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletsRoute,
} as any)
const WalletsWalletIdRoute = WalletsWalletIdRouteImport.update({
  id: '/$walletId',
  path: '/$walletId',
  getParentRoute: () => WalletsRoute,
} as any)
const VaultsVaultIdRoute = VaultsVaultIdRouteImport.update({
  id: '/$vaultId',
  path: '/$vaultId',
  getParentRoute: () => VaultsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/vault-detail': typeof VaultDetailRoute
  '/vaults': typeof VaultsRouteWithChildren
  '/wallets': typeof WalletsRouteWithChildren
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/vault-detail': typeof VaultDetailRoute
  '/vaults': typeof VaultsRouteWithChildren
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/wallets': typeof WalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/vault-detail': typeof VaultDetailRoute
  '/vaults': typeof VaultsRouteWithChildren
  '/wallets': typeof WalletsRouteWithChildren
  '/vaults/$vaultId': typeof VaultsVaultIdRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/receive'
    | '/send'
    | '/settings'
    | '/vault-detail'
    | '/vaults'
    | '/wallets'
    | '/vaults/$vaultId'
    | '/wallets/$walletId'
    | '/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/receive'
    | '/send'
    | '/settings'
    | '/vault-detail'
    | '/vaults'
    | '/vaults/$vaultId'
    | '/wallets/$walletId'
    | '/wallets'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/receive'
    | '/send'
    | '/settings'
    | '/vault-detail'
    | '/vaults'
    | '/wallets'
    | '/vaults/$vaultId'
    | '/wallets/$walletId'
    | '/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  VaultDetailRoute: typeof VaultDetailRoute
  VaultsRoute: typeof VaultsRouteWithChildren
  WalletsRoute: typeof WalletsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault-detail': {
      id: '/vault-detail'
      path: '/vault-detail'
      fullPath: '/vault-detail'
      preLoaderRoute: typeof VaultDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/': {
      id: '/wallets/'
      path: '/'
      fullPath: '/wallets/'
      preLoaderRoute: typeof WalletsIndexRouteImport
      parentRoute: typeof WalletsRoute
    }
    '/wallets/$walletId': {
      id: '/wallets/$walletId'
      path: '/$walletId'
      fullPath: '/wallets/$walletId'
      preLoaderRoute: typeof WalletsWalletIdRouteImport
      parentRoute: typeof WalletsRoute
    }
    '/vaults/$vaultId': {
      id: '/vaults/$vaultId'
      path: '/$vaultId'
      fullPath: '/vaults/$vaultId'
      preLoaderRoute: typeof VaultsVaultIdRouteImport
      parentRoute: typeof VaultsRoute
    }
  }
}

interface VaultsRouteChildren {
  VaultsVaultIdRoute: typeof VaultsVaultIdRoute
}

const VaultsRouteChildren: VaultsRouteChildren = {
  VaultsVaultIdRoute: VaultsVaultIdRoute,
}

const VaultsRouteWithChildren =
  VaultsRoute._addFileChildren(VaultsRouteChildren)

interface WalletsRouteChildren {
  WalletsWalletIdRoute: typeof WalletsWalletIdRoute
  WalletsIndexRoute: typeof WalletsIndexRoute
}

const WalletsRouteChildren: WalletsRouteChildren = {
  WalletsWalletIdRoute: WalletsWalletIdRoute,
  WalletsIndexRoute: WalletsIndexRoute,
}

const WalletsRouteWithChildren =
  WalletsRoute._addFileChildren(WalletsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  VaultDetailRoute: VaultDetailRoute,
  VaultsRoute: VaultsRouteWithChildren,
  WalletsRoute: WalletsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
